// 카이로(이집트, 아프리카) city content (spec appendix A.3). Map rows are 30 × 40 chars, legend in content/tiles.ts (27 kinds).
// 나일강(열 14~17)이 남북으로 흐르고 다리 2개(행 10~11, 20~21), 강가에 농경지·야자수, 서쪽은 사막과 피라미드, 동쪽은 시장·모스크·박물관.
import type { CityDef } from '../../types';
import { MAPFIND_COUNT, MAPFIND_PASS, MATCH_MAX_ATTEMPTS, MATCH_PAIRS, QUIZ_COUNT, QUIZ_PASS } from '../../constants';

export const CAIRO: CityDef = {
  id: 'cairo',
  name: '카이로',
  continent: 'africa',
  theme: { ground: 'sand', road: 'dirt', building: 'sandstone', tree: 'palm', streetTree: 'palm', water: 'river', wall: 'stone', bgm: 'cairo' },
  landmarks: [
    { id: 'lm_cairo_pyramids', kind: 'pyramids', at: { tx: 4, ty: 4 }, w: 4, h: 3, overhang: 1 },
    { id: 'lm_cairo_sphinx', kind: 'sphinx', at: { tx: 5, ty: 8 }, w: 2, h: 2 },
    { id: 'lm_cairo_mosque', kind: 'mosque', at: { tx: 23, ty: 16 }, w: 4, h: 3, overhang: 2 },
    { id: 'lm_cairo_museum', kind: 'museum', at: { tx: 32, ty: 14 }, w: 4, h: 3 },
  ],
  rows: [
    'RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR',
    'RSSSSSSSSSSSSF~~~~FSSSSSSSSSSSSSSSSSSSSR',
    'RSSSSSSSSSSSpF~~~~FpSSSSS####SSSS####SSR',
    'RSSSSSSSSSSSSF~~~~FSSSSSS####SSSS####SSR',
    'RSSSPPPPSSSSpF~~~~FpSSSSS####SSSS####SSR',
    'RSSSPPPPSSSSSF~~~~FSSSSSSSS==SSSSSS==SSR',
    'RSSSPPPPSSSSpF~~~~FpSSSSSSS==SSSSlS==SSR',
    'RSSSSSSSSSSSSF~~~~FSSSSSSSS==SSSSSS==SSR',
    'RSSSSPPSSSSSSF~~~~FSSSbSSSS==SSSSSS==bSR',
    'RSSSSPPSSSSSpF~~~~FpSSSSSSS==SSSSSS==SSR',
    'R=============BBBB=====================E',
    'RSSSSSSSSSSSSFBBBBFSSSSSSSSSSSSSSSSSSSSR',
    'RSSSSSSSSSSSpF~~~~FpSSSSmSmSmSSSSSSSSSSR',
    'RSSSSSSSSSSSSF~~~~FSSSSSSSSSSSSSSSSSSSSR',
    'RSSSSSSSSSSSSF~~~~FSSSmSSmSmSSSSPPPPSSSR', // row 14: stall (23,14) → (22,14), clear of the mosque's overhang (review Stage C L10)
    'RSSsSSSSSSSSpF~~~~FpSSSSSSSSSSSSPPPPSSSR',
    'RSsssSSSSSSSSF~~~~FSSSSPPPPSSSSSPPPPSSSR',
    'RSSsSSSSSSSSSF~~~~FSSSSPPPPSSSSSSSSSSSSR',
    'RSSSSSSSSSSSpF~~~~FpSSSPPPPSSSSlSSSSSSSR',
    'RSSSSSSSSSSSSF~~~~FSSSSSSSSSSSSSSSSSSSSR',
    'RSSSSS========BBBB====================SR',
    'RSSSSSSSSSSSSFBBBBFSSSSSSSSSSSSSSSSSSSSR',
    'RSSSSSSSSSSSpF~~~~FpSSSSSSSSSSSSSSSSSSSR',
    'RSSSsSSSSSSSSF~~~~FSSSSSSSSSSSsSSSSSSSSR',
    'RSSsssSSSSSSSF~~~~FSSSSSSSSSSsssSSSSSSSR',
    'RSsssssSSSSSpF~~~~FpSSSSSSSSSsssssSSSSSR',
    'RSSsssSSSSSSSF~~~~FSSSSSSSSSSsssSSSSSSSR',
    'RSSSsSSSSSSSSF~~~~FSSSSSSSSSSSsSSSSSSSSR',
    'RSSSSSSSSSSSSF~~~~FSSSSSSSSSSSSSSSSSSSSR',
    'RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR',
  ],
  entrance: { tx: 39, ty: 10 },
  spawn: { tx: 37, ty: 10 },
  spawnFacing: 'left',
  cards: [
    {
      id: 'card_cairo_geo', cityId: 'cairo', topic: 'geo', title: '카이로의 지형',
      lines: [
        '아프리카 대륙 북동쪽에 있는 이집트의 수도이다.',
        '세계에서 가장 긴 나일강(약 6,650km)이 남쪽에서 북쪽으로 흘러 지중해로 간다.',
        '이집트 땅의 대부분은 사하라 사막이라 사람들은 나일강 가의 좁은 땅에 모여 산다.',
        '도시 바로 옆 기자에 피라미드와 스핑크스가 있다.',
        '서울에서 약 8,500km 떨어져 있다.',
      ],
    },
    {
      id: 'card_cairo_climate', cityId: 'cairo', topic: 'climate', title: '카이로의 기후',
      lines: [
        '비가 거의 오지 않는 사막 기후이다(1년에 약 25mm).',
        '여름 낮은 35°C가 넘게 덥고 겨울 낮은 20°C 안팎으로 따뜻하다.',
        '낮과 밤의 기온 차가 커서 사막의 밤은 서늘하다.',
        "봄에는 '캄신'이라는 뜨거운 모래바람이 분다.",
        '서울이 낮 12시일 때 카이로는 새벽 5시(여름에는 6시)이다.',
      ],
    },
    {
      id: 'card_cairo_culture', cityId: 'cairo', topic: 'culture', title: '카이로의 문화',
      lines: [
        '아랍어를 쓰고 화폐는 이집트 파운드이다.',
        '약 4,500년 전 파라오의 무덤인 피라미드, 상형 문자, 미라 같은 고대 이집트 문명의 유산이 있다.',
        '이슬람교를 믿는 사람이 많아 모스크(이슬람 사원)가 많다.',
        '칸 엘 칼릴리 같은 전통 시장이 있고 코샤리·아이쉬(빵)를 먹는다.',
        '인구는 약 1,000만 명(주변까지 합치면 2,000만 명이 넘는다).',
      ],
    },
  ],
  signs: [
    { id: 'sign_cairo_geo', cardId: 'card_cairo_geo', at: { tx: 12, ty: 20 } },
    { id: 'sign_cairo_climate', cardId: 'card_cairo_climate', at: { tx: 8, ty: 7 } },
    { id: 'sign_cairo_culture', cardId: 'card_cairo_culture', at: { tx: 22, ty: 13 } },
  ],
  npcs: [
    {
      id: 'npc_amir', name: '아미르', role: 'guide', at: { tx: 36, ty: 11 }, facing: 'down',
      missionIds: ['m_cairo_quiz', 'm_cairo_map'], cardId: 'card_cairo_geo', bubble: '아흘란! 환영해',
      idleText: '카이로에 온 걸 환영해. 다리를 건너 서쪽으로 가면 피라미드가 보여.',
    },
    {
      id: 'npc_nadia', name: '나디아', role: 'teacher', at: { tx: 33, ty: 17 }, facing: 'down',
      missionIds: ['m_cairo_match', 'm_cairo_ox'], bubble: '박물관이야',
      idleText: '여기는 이집트 박물관이야. 미라와 파라오의 보물이 가득하지.',
    },
    {
      id: 'npc_karim', name: '카림', role: 'guard', at: { tx: 9, ty: 12 }, facing: 'down',
      missionIds: ['m_cairo_defeat'], bubble: '풍뎅이 조심!',
      idleText: '사막 남쪽 모래밭에 반짝 풍뎅이가 잔뜩 있어. 조심해!',
    },
  ],
  missions: [
    {
      id: 'm_cairo_quiz', cityId: 'cairo', giverNpcId: 'npc_amir', title: '카이로 지리 퀴즈',
      description: '아미르가 내는 카이로 퀴즈 5문제 중 4개 이상 맞히기',
      objective: { type: 'minigame', spec: { kind: 'quiz', cityId: 'cairo', count: QUIZ_COUNT, passCount: QUIZ_PASS } },
      rewardPoints: 40,
      acceptText: '카이로에 대해 얼마나 아는지 퀴즈를 내 볼게! 표지판을 먼저 읽고 오면 쉬울 거야. 준비되면 다시 말 걸어 줘.',
      progressText: '퀴즈에 도전할 준비가 됐어?',
      completeText: '대단해! 나일강처럼 지식이 길구나.',
      failText: '아깝다! 표지판을 읽고 다시 도전해 봐.',
    },
    {
      id: 'm_cairo_map', cityId: 'cairo', giverNpcId: 'npc_amir', title: '아프리카를 찾아라',
      description: '아미르가 말하는 곳을 세계지도에서 5번 중 4번 이상 찾기',
      objective: { type: 'minigame', spec: { kind: 'mapfind', cityId: 'cairo', count: MAPFIND_COUNT, passCount: MAPFIND_PASS } },
      rewardPoints: 30, prerequisiteMissionId: 'm_cairo_quiz',
      acceptText: '세계지도에서 카이로와 아프리카, 주변 바다를 찾아볼래? 준비되면 말 걸어 줘.',
      progressText: '지도 찾기에 도전할래?',
      completeText: '지도 박사구나! 아프리카는 이제 눈 감고도 찾겠어.',
      failText: '세계지도에서 아프리카 모양을 다시 살펴봐.',
    },
    {
      id: 'm_cairo_match', cityId: 'cairo', giverNpcId: 'npc_nadia', title: '카이로 짝맞추기',
      description: '나디아의 카드 6쌍을 14번 안에 모두 맞히기',
      objective: { type: 'minigame', spec: { kind: 'match', cityId: 'cairo', pairs: MATCH_PAIRS, maxAttempts: MATCH_MAX_ATTEMPTS } },
      rewardPoints: 30,
      acceptText: '이집트 카드 짝맞추기를 해 보자. 카드를 뒤집어 짝을 찾아 봐. 준비되면 말 걸어 줘.',
      progressText: '짝맞추기에 도전할래?',
      completeText: '기억력이 파라오급이야!',
      failText: '카드 위치를 기억하며 다시 해 보자.',
    },
    {
      id: 'm_cairo_ox', cityId: 'cairo', giverNpcId: 'npc_nadia', title: '카이로 OX 퀴즈',
      description: '나디아가 내는 OX 퀴즈 5문제 중 4개 이상 맞히기',
      objective: { type: 'minigame', spec: { kind: 'ox', cityId: 'cairo', count: QUIZ_COUNT, passCount: QUIZ_PASS } },
      rewardPoints: 30, prerequisiteMissionId: 'm_cairo_match',
      acceptText: '이집트의 기후와 문화에 대해 OX 퀴즈를 내 볼게. 준비되면 다시 말 걸어 줘!',
      progressText: 'OX 퀴즈에 도전해 볼래?',
      completeText: '훌륭해! 사막 기후를 정확히 알고 있구나.',
      failText: '아깝다! 표지판을 읽고 다시 도전해 봐.',
    },
    {
      id: 'm_cairo_defeat', cityId: 'cairo', giverNpcId: 'npc_karim', title: '반짝 풍뎅이 소탕',
      description: '사막 모래밭의 반짝 풍뎅이 3마리 처치',
      objective: { type: 'defeat', monsterId: 'scarab', count: 3 },
      rewardPoints: 30,
      acceptText: '사막의 반짝 풍뎅이가 시장까지 내려와. 3마리만 뿅 하고 쫓아 줄래? F 키로 공격할 수 있어.',
      progressText: '풍뎅이는 아직 남아 있어?',
      completeText: '슈크란(고마워)! 덕분에 시장이 조용해졌어.',
    },
  ],
  monsterZones: [
    { monsterId: 'scarab', center: { tx: 4, ty: 25 }, radiusTiles: 3, count: 3 },
    { monsterId: 'scarab', center: { tx: 31, ty: 25 }, radiusTiles: 3, count: 3 },
    { monsterId: 'mummy_cat', center: { tx: 3, ty: 16 }, radiusTiles: 2, count: 2 },
  ],
  // every mission counts toward the stamp (spec 8.2, 14.5)
  stampMissionIds: ['m_cairo_quiz', 'm_cairo_map', 'm_cairo_match', 'm_cairo_ox', 'm_cairo_defeat'],
};
