// Paris city content (v0.2 spec A.2). Map rows are 30 × 40 chars, legend in content/tiles.ts (27 kinds).
import type { CityDef } from '../../types';
import { BLANK_COUNT, BLANK_PASS, ORDER_COUNT, ORDER_PASS, ORDER_TRIES, QUIZ_COUNT, QUIZ_PASS } from '../../constants';

export const PARIS: CityDef = {
  id: 'paris',
  name: '파리',
  continent: 'europe',
  theme: { ground: 'grass', road: 'cobble', building: 'parisian', tree: 'round', streetTree: 'plane', water: 'river', wall: 'hedge', bgm: 'paris' },
  landmarks: [
    { id: 'lm_paris_arc', kind: 'arc', at: { tx: 4, ty: 5 }, w: 2, h: 2, overhang: 1 },
    { id: 'lm_paris_louvre', kind: 'louvre', at: { tx: 24, ty: 3 }, w: 8, h: 3, overhang: 1 },
    { id: 'lm_paris_notredame', kind: 'notredame', at: { tx: 23, ty: 16 }, w: 2, h: 2, overhang: 2 },
    { id: 'lm_paris_eiffel', kind: 'eiffel', at: { tx: 4, ty: 21 }, w: 2, h: 2, overhang: 3 },
  ],
  rows: [
    'RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR',
    'RRRRRRRTTRRRTTTRRRRTTRRRRRRTTTRRRRRRTTRR',
    'TRRRR..................................T',
    'T.......##..##..........PPPPPPPP.......T',
    'T.......##..##..........PPPPPPPP.......T',
    'T...PP..........==......PPPPPPPP..==...T',
    'T...PP..........==..............t.==...T',
    'T.......*.......==..l...........t.==...T',
    'T.=============.==..####........t.==...T',
    'T.......l.......==..####........t.==...T',
    'T=====================================.E',
    'T...**..........==....**....**....==...T',
    'T..####.........==....####..####..==...T',
    'T..####.........==....####..####..==...T',
    'T.......b.......==..........b.....==...T',
    'T~~~~~~~~~~~~~~~BB~~BB~~~~~~~~~~~~BB~~~T',
    'T~~~~~~~~~~~~~..BB.....PP.~~~~~~~~BB~~~T',
    'T~~~~~~~~~~~~~..BB.....PP.~~~~~~~~BB~~~T',
    'T~~~~~~~~~~~~~~~BB~~BB~~~~~~~~~~~~BB~~~T',
    'T...............==................==...T',
    'T====================================..T',
    'T...PP..........,,....*.........,,,....T',
    'T...PP.........,,,,..........T.,,,,,...T',
    'T..............,,,,,,........T.,,,,,...T',
    'T....,,,.......,,,,,,..........,,,,,...T',
    'T...,,,,,.......,,,,......T.....,,,....T',
    'T....,,,....l.....................T....T',
    'T.......T.............T................T',
    'T......................................T',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  ],
  entrance: { tx: 39, ty: 10 },
  spawn: { tx: 37, ty: 10 },
  spawnFacing: 'left',
  cards: [
    {
      id: 'card_paris_geo', cityId: 'paris', topic: 'geo', title: '파리의 지형',
      lines: [
        '유럽 대륙 서쪽에 있는 프랑스의 수도이다.',
        '센강이 도시 가운데를 흐르고 강 가운데에 시테섬이 있다.',
        '넓고 평평한 파리 분지(평야) 위에 있어 높은 산이 없다.',
        '가장 높은 곳은 몽마르트르 언덕(약 130m)이다.',
        '서울에서 약 9,000km 떨어져 있어 비행기로 12시간 넘게 걸린다.',
      ],
    },
    {
      id: 'card_paris_climate', cityId: 'paris', topic: 'climate', title: '파리의 기후',
      lines: [
        '대서양과 편서풍의 영향을 받는 서안 해양성 기후이다.',
        '여름은 서울보다 덜 덥고, 겨울은 서울보다 따뜻하다.',
        '비가 1년 내내 고르게 조금씩 내린다(1년 약 640mm).',
        '흐리고 가랑비가 내리는 날이 많다.',
        '서울이 낮 12시일 때 파리는 새벽 4시(여름에는 5시)로, 서울보다 시간이 느리다.',
      ],
    },
    {
      id: 'card_paris_culture', cityId: 'paris', topic: 'culture', title: '파리의 문화',
      lines: [
        '프랑스어를 쓰고 화폐는 유로를 쓴다.',
        '1889년에 세운 에펠탑, 모나리자가 있는 루브르 박물관, 개선문이 있다.',
        '바게트·크루아상을 먹고 카페에서 이야기 나누는 문화가 있다.',
        '프랑스 국기는 파랑·하양·빨강 삼색기이다.',
        '2024년 여름 올림픽이 열렸다.',
      ],
    },
  ],
  signs: [
    { id: 'sign_paris_geo', cardId: 'card_paris_geo', at: { tx: 13, ty: 14 } },
    { id: 'sign_paris_climate', cardId: 'card_paris_climate', at: { tx: 8, ty: 7 } },
    { id: 'sign_paris_culture', cardId: 'card_paris_culture', at: { tx: 8, ty: 22 } },
  ],
  npcs: [
    {
      id: 'npc_marie', name: '마리', role: 'guide', at: { tx: 36, ty: 8 }, facing: 'down',
      missionIds: ['m_paris_quiz', 'm_paris_blank'], cardId: 'card_paris_geo', bubble: '봉주르!',
      idleText: '봉주르! 파리에 온 걸 환영해. 센강 다리를 건너면 에펠탑이 보여.',
    },
    {
      id: 'npc_louis', name: '루이', role: 'teacher', at: { tx: 27, ty: 7 }, facing: 'down',
      missionIds: ['m_paris_ox', 'm_paris_order'], bubble: '루브르야!',
      idleText: '여기는 루브르 박물관이야. 모나리자가 이 안에 있지.',
    },
    {
      // (14,19) in v0.1 → (12,19): keeps 96px+ from the pigeon zone at (18,23) (spec A.2)
      id: 'npc_pierre', name: '피에르', role: 'guard', at: { tx: 12, ty: 19 }, facing: 'down',
      missionIds: ['m_paris_defeat'], bubble: '비둘기 조심!',
      idleText: '에펠탑 공원의 비둘기들이 빵 부스러기를 노리고 있어. 조심해!',
    },
  ],
  missions: [
    {
      id: 'm_paris_quiz', cityId: 'paris', giverNpcId: 'npc_marie', title: '파리 지리 퀴즈',
      description: '마리가 내는 파리 퀴즈 5문제 중 4개 이상 맞히기',
      objective: { type: 'minigame', spec: { kind: 'quiz', cityId: 'paris', count: QUIZ_COUNT, passCount: QUIZ_PASS } },
      rewardPoints: 40,
      acceptText: '파리에 대해 퀴즈를 내 볼게! 표지판을 먼저 읽고 오면 더 쉬울 거야. 준비되면 다시 말 걸어 줘.',
      progressText: '퀴즈에 도전할 준비가 됐어?',
      completeText: '트레비앙! 파리를 정말 잘 아는구나.',
      failText: '아깝다! 표지판을 읽고 다시 도전해 봐.',
    },
    {
      id: 'm_paris_ox', cityId: 'paris', giverNpcId: 'npc_louis', title: '파리 OX 퀴즈',
      description: '루이가 내는 OX 퀴즈 5문제 중 4개 이상 맞히기',
      objective: { type: 'minigame', spec: { kind: 'ox', cityId: 'paris', count: QUIZ_COUNT, passCount: QUIZ_PASS } },
      rewardPoints: 30,
      acceptText: '파리의 기후와 지형에 대해 OX 퀴즈를 내 볼게. 준비되면 다시 말 걸어 줘!',
      progressText: 'OX 퀴즈에 도전해 볼래?',
      completeText: '멋져! 서울과 파리의 차이를 잘 이해했구나.',
      failText: '아깝다! 표지판을 읽고 다시 도전해 봐.',
    },
    {
      id: 'm_paris_defeat', cityId: 'paris', giverNpcId: 'npc_pierre', title: '심술 비둘기 소탕',
      description: '에펠탑 공원의 심술 비둘기 3마리 처치',
      objective: { type: 'defeat', monsterId: 'pigeon', count: 3 },
      rewardPoints: 30,
      acceptText: '에펠탑 공원에 심술 비둘기가 너무 많아. 3마리만 쫓아내 줄래? F 키로 공격할 수 있어.',
      progressText: '비둘기는 아직 남아 있어?',
      completeText: '메르시! 덕분에 공원이 조용해졌어.',
    },
    // v0.2 follow-up missions (spec 8.3, A.2): bonus only — not part of stampMissionIds (spec 14.5)
    {
      id: 'm_paris_blank', cityId: 'paris', giverNpcId: 'npc_marie', title: '파리 빈칸 채우기',
      description: '마리의 문장 4개 중 3개 이상 빈칸 채우기',
      objective: { type: 'minigame', spec: { kind: 'blank', cityId: 'paris', count: BLANK_COUNT, passCount: BLANK_PASS } },
      rewardPoints: 30, prerequisiteMissionId: 'm_paris_quiz',
      acceptText: '이번엔 문장의 빈칸을 채워 볼까? 보기 중에서 알맞은 말을 골라 봐.',
      progressText: '빈칸 채우기에 도전할래?',
      completeText: '파르페(완벽해)! 파리를 문장으로도 설명할 수 있구나.',
      failText: '표지판의 문장을 다시 읽어 보고 도전해 봐.',
    },
    {
      id: 'm_paris_order', cityId: 'paris', giverNpcId: 'npc_louis', title: '순서대로 맞추기',
      description: '루이의 순서 문제 2개를 모두 맞히기(문제당 2번까지)',
      objective: { type: 'minigame', spec: { kind: 'order', cityId: 'paris', count: ORDER_COUNT, passCount: ORDER_PASS, triesPerQuestion: ORDER_TRIES } },
      rewardPoints: 30, prerequisiteMissionId: 'm_paris_ox',
      acceptText: '박물관답게 순서 문제야. 오래된 것부터, 가까운 것부터 늘어놓아 봐.',
      progressText: '순서 맞추기에 도전할래?',
      completeText: '역사와 지리를 한 줄로 꿰었구나. 브라보!',
      failText: '카드 아래 숫자를 떠올리며 다시 해 보자.',
    },
  ],
  monsterZones: [
    { monsterId: 'pigeon', center: { tx: 6, ty: 25 }, radiusTiles: 2, count: 3 },
    { monsterId: 'pigeon', center: { tx: 18, ty: 23 }, radiusTiles: 3, count: 3 },
    { monsterId: 'gargoyle', center: { tx: 33, ty: 23 }, radiusTiles: 3, count: 3 },
  ],
  stampMissionIds: ['m_paris_quiz', 'm_paris_ox', 'm_paris_defeat'],
};
