// 시드니(오스트레일리아, 오세아니아) city content (spec appendix A.5). Map rows are 30 × 40 chars, legend in content/tiles.ts (27 kinds).
// 북쪽 항구(행 2~11)를 하버 브리지(열 14~15)가 남북으로 잇고 북쪽 기슭 산책로(행 1 열 14~15)까지 걸어갈 수 있다. 서큘러 키 산책로(행 12), 도심 블록(행 13~14, 광장 열 19~22), 남서쪽 공원, 남동쪽 본다이 해변, 동쪽 바다.
import type { CityDef } from '../../types';
import { BLANK_COUNT, BLANK_PASS, MAPFIND_COUNT, MAPFIND_PASS, MATCH_MAX_ATTEMPTS, MATCH_PAIRS, QUIZ_COUNT, QUIZ_PASS } from '../../constants';

export const SYDNEY: CityDef = {
  id: 'sydney',
  name: '시드니',
  continent: 'oceania',
  theme: { ground: 'grass', road: 'asphalt', building: 'modern', tree: 'gum', streetTree: 'palm', water: 'sea', wall: 'hedge', bgm: 'sydney' },
  landmarks: [
    // 항구로 튀어나온 곶 위 (A.5)
    { id: 'lm_sydney_opera', kind: 'opera', at: { tx: 22, ty: 9 }, w: 4, h: 2, overhang: 2 },
    // 다리 타일 'B' 위 아치 오버레이: 충돌 없이 그림만 얹고, 플레이어는 아래 다리를 걸어서 건넌다 (A.5)
    { id: 'lm_sydney_bridge', kind: 'harbour_bridge', at: { tx: 14, ty: 2 }, w: 2, h: 8, overhang: 1, solid: false },
  ],
  rows: [
    '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
    '~~TTTTTTTTTTTT..TTTTTTTTTTTTTTTTTTTTTT~~',
    '~~T.....~~~~~~BB~~~~~~~~~~~~~~~~.....T~~',
    '~~T.b...~~~~~~BB~~~~~~~~~~~~~~~~...b.T~~',
    '~~T.....~~~~~~BB~~~~~~~~~~~~~~~~.....T~~',
    '~~TT.T..~~~~~~BB~~~~~~~~~~~~~~~~..T..T~~',
    '~~T.....~~~~~~BB~~~~~~~~~~~~~~~~.....T~~',
    '~~T..l..~~~~~~BB~~~~~~~~~~~~~~~~..l..T~~',
    '~~T.....~~~~~~BB~~~~~~QQQQ~~~~~~.....T~~',
    '~~T.....~~~~~~BB~~~~~~PPPP~~~~~~.....T~~',
    '~~T.....~~~~~~BB~~~~~~PPPP~~~~~~.....T~~',
    '~~T..............~~~~~QQQQ~~~~~......T~~',
    '~~T----------------------------------T~~',
    '~~T-####-####-####-QQQQ-####-####-##-T~~',
    '~~T-####-####-####-QQQQ-####-####-##-T~~',
    '~~T====================================E',
    '~~T...........-####-####-............T~~',
    '~~T..T.....T..-####-####-....T.......T~~',
    '~~T...........-----------............T~~',
    '~~T..,,,...........l.........SSSSSSS~~~~',
    '~~T.,,,,,...................SSSSSSSS~~~~',
    '~~T..,,,..........T........SSSSSSSSS~~~~',
    '~~T........................SSSSsSSSS~~~~',
    '~~T....T........-####-....SSSSsssSSS~~~~',
    '~~T.............-####-....SSSSSsSSSS~~~~',
    '~~T......,,,..............SSSSSSSSSS~~~~',
    '~~T.....,,,,,......b.....SSSSSSSSSSS~~~~',
    '~~T......,,,.............SSSSSSSSSSS~~~~',
    '~~TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT~~~~',
    '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
  ],
  entrance: { tx: 39, ty: 15 },
  spawn: { tx: 37, ty: 15 },
  spawnFacing: 'left',
  cards: [
    {
      id: 'card_sydney_geo', cityId: 'sydney', topic: 'geo', title: '시드니의 지형',
      lines: [
        '오세아니아 대륙(오스트레일리아) 남동쪽 바닷가에 있는 오스트레일리아에서 가장 큰 도시이다(인구 약 540만 명).',
        '세계에서 손꼽히게 큰 천연 항구(시드니 항)를 둘러싸고 도시가 있다.',
        '항구에 돛 모양 지붕의 오페라 하우스와 하버 브리지가 있다.',
        '서쪽에는 유칼립투스 숲으로 덮인 블루마운틴이 있고 대륙 안쪽은 넓은 사막이다.',
        '서울에서 약 8,300km, 비행기로 10시간쯤 걸린다.',
      ],
    },
    {
      id: 'card_sydney_climate', cityId: 'sydney', topic: 'climate', title: '시드니의 기후',
      lines: [
        '남반구에 있어 계절이 우리나라와 반대이다(12~2월이 여름).',
        '여름(1월 평균 약 23°C)은 따뜻하고 겨울(7월 평균 약 13°C)은 포근해 눈이 거의 오지 않는다.',
        '비는 1년 내내 고르게 내리며 1년 약 1,200mm이다.',
        '크리스마스를 여름 해변에서 보낸다.',
        '서울이 낮 12시일 때 시드니는 오후 1시(호주 여름에는 2시)이다.',
      ],
    },
    {
      id: 'card_sydney_culture', cityId: 'sydney', topic: 'culture', title: '시드니의 문화',
      lines: [
        '영어를 쓰고 화폐는 오스트레일리아 달러이다.',
        '오스트레일리아의 수도는 시드니가 아니라 캔버라이다.',
        '원주민 애버리지니의 부메랑·디저리두 문화가 있고 여러 나라에서 온 이민자가 함께 산다.',
        '캥거루·코알라·오리너구리처럼 다른 대륙에는 없는 동물이 산다.',
        '국기에는 남십자성 별이 있고 2000년에 시드니 올림픽이 열렸다.',
      ],
    },
  ],
  signs: [
    { id: 'sign_sydney_geo', cardId: 'card_sydney_geo', at: { tx: 16, ty: 11 } },
    { id: 'sign_sydney_climate', cardId: 'card_sydney_climate', at: { tx: 12, ty: 17 } },
    { id: 'sign_sydney_culture', cardId: 'card_sydney_culture', at: { tx: 20, ty: 13 } },
  ],
  npcs: [
    {
      id: 'npc_olivia', name: '올리비아', role: 'guide', at: { tx: 36, ty: 16 }, facing: 'down',
      missionIds: ['m_sydney_quiz', 'm_sydney_match'], cardId: 'card_sydney_geo', bubble: '굿다이! 시드니야',
      idleText: '항구 쪽으로 가면 오페라 하우스와 하버 브리지가 보여.',
    },
    {
      id: 'npc_jack', name: '잭', role: 'teacher', at: { tx: 23, ty: 12 }, facing: 'down',
      missionIds: ['m_sydney_map', 'm_sydney_blank'], bubble: '오페라 하우스야',
      idleText: '돛 모양 지붕 보여? 1973년에 완성된 오페라 하우스야.',
    },
    {
      id: 'npc_ruby', name: '루비', role: 'guard', at: { tx: 26, ty: 18 }, facing: 'down',
      missionIds: ['m_sydney_defeat'], bubble: '갈매기 조심!',
      idleText: '해변의 갈매기가 감자튀김을 노려. 조심해!',
    },
  ],
  missions: [
    {
      id: 'm_sydney_quiz', cityId: 'sydney', giverNpcId: 'npc_olivia', title: '시드니 지리 퀴즈',
      description: '올리비아가 내는 시드니 퀴즈 5문제 중 4개 이상 맞히기',
      objective: { type: 'minigame', spec: { kind: 'quiz', cityId: 'sydney', count: QUIZ_COUNT, passCount: QUIZ_PASS } },
      rewardPoints: 40,
      acceptText: '시드니에 대해 퀴즈를 내 볼게! 표지판을 먼저 읽고 오면 쉬울 거야. 준비되면 다시 말 걸어 줘.',
      progressText: '퀴즈에 도전할 준비가 됐어?',
      completeText: '노 워리스! 완벽해. 시드니 박사라고 불러도 되겠어.',
      failText: '아깝다! 표지판을 읽고 다시 도전해 봐.',
    },
    {
      id: 'm_sydney_match', cityId: 'sydney', giverNpcId: 'npc_olivia', title: '시드니 짝맞추기',
      description: '올리비아의 카드 6쌍을 14번 안에 모두 맞히기',
      objective: { type: 'minigame', spec: { kind: 'match', cityId: 'sydney', pairs: MATCH_PAIRS, maxAttempts: MATCH_MAX_ATTEMPTS } },
      rewardPoints: 30, prerequisiteMissionId: 'm_sydney_quiz',
      acceptText: '이번엔 카드 짝맞추기! 오스트레일리아 동물과 명소 짝을 찾아 봐.',
      progressText: '짝맞추기에 도전할래?',
      completeText: '기억력이 코알라급… 아니 캥거루급이야!',
      failText: '카드 위치를 기억하며 다시 해 보자.',
    },
    {
      id: 'm_sydney_map', cityId: 'sydney', giverNpcId: 'npc_jack', title: '남반구를 찾아라',
      description: '잭이 말하는 곳을 세계지도에서 5번 중 4번 이상 찾기',
      objective: { type: 'minigame', spec: { kind: 'mapfind', cityId: 'sydney', count: MAPFIND_COUNT, passCount: MAPFIND_PASS } },
      rewardPoints: 30,
      acceptText: '세계지도에서 시드니와 오세아니아, 주변 바다를 찾아볼래? 준비되면 말 걸어 줘.',
      progressText: '지도 찾기에 도전할래?',
      completeText: '지도 박사구나! 남반구는 이제 눈 감고도 찾겠어.',
      failText: '세계지도에서 오세아니아 위치를 다시 살펴봐.',
    },
    {
      id: 'm_sydney_blank', cityId: 'sydney', giverNpcId: 'npc_jack', title: '시드니 빈칸 채우기',
      description: '잭의 문장 4개 중 3개 이상 빈칸 채우기',
      objective: { type: 'minigame', spec: { kind: 'blank', cityId: 'sydney', count: BLANK_COUNT, passCount: BLANK_PASS } },
      rewardPoints: 30, prerequisiteMissionId: 'm_sydney_map',
      acceptText: '이번엔 문장 빈칸이야. 남반구의 계절을 떠올리며 골라 봐.',
      progressText: '빈칸 채우기에 도전할래?',
      completeText: '완벽해! 남반구의 계절까지 정확히 알고 있구나.',
      failText: '표지판 문장을 다시 읽고 도전해 봐.',
    },
    {
      id: 'm_sydney_defeat', cityId: 'sydney', giverNpcId: 'npc_ruby', title: '심술 갈매기 소탕',
      description: '본다이 해변의 심술 갈매기 3마리 처치',
      objective: { type: 'defeat', monsterId: 'seagull', count: 3 },
      rewardPoints: 30,
      acceptText: '해변의 갈매기가 감자튀김을 자꾸 훔쳐 가. 3마리만 뿅 하고 쫓아 줄래? F 키로 공격할 수 있어.',
      progressText: '갈매기는 아직 남아 있어?',
      completeText: '땡스 메이트! 덕분에 해변이 평화로워졌어.',
    },
  ],
  monsterZones: [
    { monsterId: 'kangaroo', center: { tx: 6, ty: 20 }, radiusTiles: 2, count: 3 },
    { monsterId: 'kangaroo', center: { tx: 8, ty: 26 }, radiusTiles: 2, count: 2 },
    { monsterId: 'seagull', center: { tx: 31, ty: 23 }, radiusTiles: 3, count: 3 },
  ],
  // every mission counts toward the stamp (spec 8.2, 14.5)
  stampMissionIds: ['m_sydney_quiz', 'm_sydney_match', 'm_sydney_map', 'm_sydney_blank', 'm_sydney_defeat'],
};
